import "../../globals.css";
import type { Metadata } from "next";
import Sidebar from "./Sidebar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <main className="md:flex">
          <div className="md:w-1/4 md:fixed">
            <Sidebar />
          </div>
          <div className="flex-1 md:ml-72 flex flex-col">{children}</div>
        </main>
      </body>
    </html>
  );
}
