import "../globals.css";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <h1 className="text-orange-500 font-bold text-2xl p-2">
            ztech18.com
          </h1>
        </div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
